version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2

commands:
  publish-snapcraft:
    description: build and push snapcraft
    machine:
      image: ubuntu-2004:202104-01
    resource_class: 2xlarge
    parameters:
      channel:
        type: string
        default: "edge"
        description: snapcraft channel
      snap-name:
        type: string
        default: 'lotus-filecoin'
        description: name of snap in snap store
    steps:
      - checkout
      - run:
          name: Install snapcraft
          command: sudo snap install snapcraft --classic
      - run:
          name: Build << parameters.snap-name >> snap
          command: |
            if [ "<< parameters.snap-name >>" != 'lotus-filecoin' ]; then
              cat snap/snapcraft.yaml | sed 's/lotus-filecoin/lotus/' > edited-snapcraft.yaml
              mv edited-snapcraft.yaml snap/snapcraft.yaml
            fi

            snapcraft --use-lxd --debug
      - run:
          name: Publish snap to << parameters.channel >> channel
          shell: /bin/bash -o pipefail
          command: |
            snapcraft upload *.snap --release << parameters.channel >>

workflows:
  version: 2.1
  ci:
    jobs:
      - publish-snapcraft:
          name: "Publish Snapcraft (lotus-filecoin / candidate)"
          channel: stable
          snap-name: lotus-filecoin
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - snapcraft-deprecation
      - publish-snapcraft:
          name: "Publish Snapcraft (lotus-filecoin / candidate)"
          channel: candidate
          snap-name: lotus-filecoin
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - snapcraft-deprecation
      - publish-snapcraft:
          name: "Publish Snapcraft (lotus / stable)"
          channel: stable
          snap-name: lotus
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - snapcraft-deprecation
      - publish-snapcraft:
          name: "Publish Snapcraft (lotus / candidate)"
          channel: candidate
          snap-name: lotus
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - snapcraft-deprecation
      - publish-snapcraft:
          name: "Publish Snapcraft Nightly (lotus-filecoin / edge)"
          channel: edge
          snap-name: lotus-filecoin
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - snapcraft-deprecation
      - publish-snapcraft:
          name: "Publish Snapcraft Nightly (lotus / edge)"
          channel: edge
          snap-name: lotus
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - snapcraft-deprecation
